Add support for PAYMETHOD parameter
newPOPE/gp-webpay-php-sdk pull request #11
Opened 2022-03-02 07:27 UTC by pavol-tuka

Allow to set different payment method (https://www.gpwebpay.cz/downloads/GP_webpay_HTTP_EN.pdf):
```
CRD – payment card
GPAY – GooglePay
APAY – Apple Pay
BTNCS – Platba 24
SOFORT
EPS
PAYSAFECARD
SEPADIRECTDEBIT
KLARNA
```

2022-03-02 08:12 UTC, newPOPE commented
Hello,

what about creating Enum with paymethod-s for easiest access to correct values via constants?

2022-03-02 08:17 UTC, pavol-tuka commented
It would be nice to have feature. More robust solution would create `PaymentRequestInterface` which allow developer to implement custom PaymentRequest which can be used to set all parameters, not only PAYMETHOD.

2022-03-04 07:30 UTC, pavol-tuka commented
Constants added.

2022-03-04 08:49 UTC, newPOPE requested changes

2022-03-04 08:49 UTC, newPOPE commented on src/AdamStipak/Webpay/PaymentRequest.php
> +use AdamStipak\Webpay\PaymentRequest\PaymentMethod;
Not sure that this class exists, if not pls delete it.

2022-03-04 08:54 UTC, merged